name: AI PR Review (Ollama)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout repo
        uses: akhioafk/ai-pr-reviewer-aqua@main

      - name: Run AI Reviewer
        env:
          OLLAMA_BASE_URL: http://localhost:11434
          OPENAI_API_BASE_URL: http://localhost:11434/v1
          OPENAI_API_KEY: ollama
          MODEL_NAME: deepseek-coder-v2:16b-lite-instruct-q4_K_M
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          cd ai-pr-reviewer
          npx ai-pr-reviewer
